
mail:
  host: smtp.yandex.ru
  port: 465
  username: kirill7195@yandex.ru
  password: tbnritrsqkiexjjb
  protocol: smtps
  tls: true
  auth: true

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:~/test
    driverClassName: org.h2.Driver
    username: sa
    password: 123
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: kafka:9001

server:
  port: 8008

